"use client";
import { useRegisterMutation } from "@/src/lib/features/api/apiSlice";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { AiOutlineEye, AiOutlineEyeInvisible } from "react-icons/ai";

interface RegistrationData {
  name: string;
  email: string;
  password: string;
}

export default function SignUp() {
  const [register, { isSuccess, isLoading }] = useRegisterMutation();
  const [user, setUser] = useState<RegistrationData>({
    name: "",
    email: "",
    password: "",
  });
  const [showPassword, setShowPassword] = useState(false);
  const router = useRouter();

  const handleSignUp = async () => {
    try {
      await register(user).unwrap();
    } catch (err: any) {
      const errorMessage = err?.data?.message || "Registration failed";
      toast.error(errorMessage);
    }
  };
  useEffect(() => {
    if (isSuccess) {
      if (isSuccess) {
        toast.success("Registration Successful");
        setUser({ name: "", email: "", password: "" });
        setTimeout(() => router.push("/auth/sign-in"), 1000);
      }
    }
  }, [isSuccess]);
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/blog.svg" />
      </Head>
      <div className="flex items-center justify-center min-h-screen font-outfit">
        <div className="bg-gray-200 p-8 rounded shadow-md">
          <h1 className="text-2xl font-semibold mb-4 text-center">Sign Up</h1>
          <div>
            <div className="mb-4">
              <label className="label-style" htmlFor="name">
                Name <span className="text-red-500">*</span>
              </label>
              <input
                className="input-style"
                id="name"
                type="text"
                placeholder="Enter your name"
                required
                value={user.name}
                onChange={(e) =>
                  setUser((data) => ({ ...data, name: e.target.value }))
                }
              />
            </div>
            <div className="mb-4">
              <label className="label-style" htmlFor="email">
                Email <span className="text-red-500">*</span>
              </label>
              <input
                className="input-style"
                id="email"
                type="email"
                placeholder="Enter your email address"
                required
                value={user.email}
                onChange={(e) =>
                  setUser((data) => ({ ...data, email: e.target.value }))
                }
              />
            </div>
            <div className="mb-4 relative">
              <label className="label-style" htmlFor="password">
                Password <span className="text-red-500">*</span>
              </label>
              <input
                className="input-style"
                id="password"
                type={!showPassword ? "password" : "text"}
                placeholder="Enter your password"
                required
                value={user.password}
                onChange={(e) =>
                  setUser((data) => ({ ...data, password: e.target.value }))
                }
              />
              {!showPassword ? (
                <AiOutlineEyeInvisible
                  className="absolute bottom-3 right-2 z-1 cursor-pointer text-black"
                  size={20}
                  onClick={() => setShowPassword(true)}
                />
              ) : (
                <AiOutlineEye
                  className="absolute bottom-3 right-2 z-1 cursor-pointer text-black "
                  size={20}
                  onClick={() => setShowPassword(!true)}
                />
              )}
            </div>

            <div className="flex items-center space-x-4">
              <button className="button-style" onClick={handleSignUp}>
                {isLoading ? "Loading..." : "Sign-Up "}
              </button>
              <p className="text-center">
                Already have account{" "}
                <span
                  className="text-gray-500 hover:underline cursor-pointer"
                  onClick={() => router.push("/auth/sign-in")}
                >
                  Sign In
                </span>{" "}
                here
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
