import Head from "next/head";
import Hero from "../components/molecules/hero";
import RecentBlogs from "../components/molecules/recent-blogs";

export default function Home({ data }: any) {
  return (
    <>
      <Head>
        <title>ArticleArc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-4">
        <Hero />
        <RecentBlogs />
      </div>
    </>
  );
}
