import Head from "next/head";
import Home from "../components/molecules/home";

export default function Page() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/blog.svg" />
      </Head>
      <div>
        <Home />
      </div>
    </>
  );
}
